### ISSUE TITLE
Run function for the CLI!

### ISSUE THREAD

**Issue by ecasilla** [finnp/test-anything#4]
No test-anything run function defined in the challenges i think we should try to keep the node school api consistent by having a run function available even if it only passes the call execution to verify for now

**Comment by finnp** [comment]
Thank you that's good feedback. The problem is that while other workshopper usually only run your code once or twice, i am checking against failing and passing code. But I added some instructions how to run the code yourself when someone tries to do `test-anything run`, so they won't see the error.

Could you have a look and give some feedback about it?

**Comment by ecasilla** [comment]
Awesome thanks will take a look and let you know how it works.
